### ISSUE TITLE
New version on PyPi?

### ISSUE THREAD

**Issue by predatell** [AuthorizeNet/sdk-python#103]
With this pull request: https://github.com/AuthorizeNet/sdk-python/pull/102

Many users want it:
https://github.com/AuthorizeNet/sdk-python/issues/100, https://github.com/AuthorizeNet/sdk-python/issues/98, https://github.com/AuthorizeNet/sdk-python/issues/97

**Comment by Sapbasu15** [comment]
We have merged the pull request #102 for the issues and will release new sdk version on PyPi soon.

**Comment by Sapbasu15** [comment]
@sanaani  We have already release the new sdk version in PyPi
