### ISSUE TITLE
PyXB version 1.2.6

### ISSUE THREAD

**Issue by predatell** [AuthorizeNet/sdk-python#112]
The latest version of PyXB is 1.2.6. It was released on Sep 2017 with fixes of bugs:

http://pyxb.sourceforge.net/releases.html#sep-2017

**Comment by chsriniv9** [comment]
@predatell 
Below are the steps to follow for upgrading PyXB version from 1.2.5 (or any older version) to 1.2.6 (latest).

1. Run the command in CMD prompt "pip install pyxb==1.2.6" or "pip install PyXB --upgrade" (in the same drive where Python is installed).
2. You will be seeing a warning message that "authorizenet 1.1.0 has requirement pyxb==1.2.5, but you'll have pyxb 1.2.6 which is incompatible.". To correct this, we need to update all the PyXB dependencies from 1.2.5 to 1.2.6 in the entire project.
3. In \setup.py, update to install_requires=['pyxb==1.2.6', 'lxml==4.*', 'requests==2.*'],
4. In \script\binding.py and \authorizenet\apicontractsv1.py, update to _PyXBVersion = '1.2.6' 
5. In\.travis.yml, update to pip install pyxb==1.2.6
6. Run the \script\generateObjectsFromXSD.bat batch file from the terminal as mentioned in \DESCRIPTION.rst file. 
7. In PyCharm IDE, File→ Settings→ Project Interpreter→ sdk-python project / sample-code-python project, Verify that PyXB version is showing as 1.2.6.
8. Run sample code to make API requests.

**Comment by chsriniv9** [comment]
@predatell 
Based on the inputs provided by previously, closing this issue. Please feel free to re-open if you need any further assistance.

**Comment by predatell** [comment]
I think this issue must be closed when app will have requirements for PyXB version 1.2.6 (current version of package)

**Comment by chsriniv9** [comment]
1. If any developer wants to upgrade to PyXB 1.2.6, it can be upgraded with the steps mentioned in the post.
2. We don’t have a compelling reason to shift sdk-python to new version of PyXB 1.2.6

Please let us know any specific fixe(s) / enhancement(s) of 1.2.6 has that benefits wider developer community for us to evaluate. Thank you for your support in advance

**Comment by predatell** [comment]
1. Is current package official package of AuthorizeNet ? Any developer can be involved in development?
2. I have already sent you link(http://pyxb.sourceforge.net/releases.html#sep-2017) where you can read about "any specific fixe(s) / enhancement(s) of 1.2.6". As I know the goal of any new release of package is "fixe(s) / enhancement(s)".
3. What can be a reason to use old version of library and to send users messages like this "the error is coming from the pyxb library..." (https://github.com/AuthorizeNet/sdk-python/issues/109) ? What can be a reason for upgrading to latest stable version of any related package?

**Comment by jhiggins** [comment]
The PyXB author has expressed that he is not really interested in continuing maintenance of the library, perhaps it is time to consider a replacement?

https://github.com/pabigot/pyxb/issues/100

**Comment by scottie** [comment]
yet here we are 5 years later....
