### ISSUE TITLE
Multiple Accepting Headers

### ISSUE THREAD

**Issue by sampocs** [AuthorizeNet/sdk-python#117]
I'm using the python-SDK in an AWS Lambda function and I noticed the following in my logs:

[WARNING]	2018-09-17T19:53:00.466Z	47785214-bab3-11e8-a21c-b3b49941b23e	Multiple accepting paths for <class 'authorizenet.apicontractsv1.**CTD_ANON_39**'>

This same type of message is shown in the log for each api call, except the **CTD_ANON_##** appears to change based on the type of API call I'm making. Could you provide any insight into what this warning means?

Thanks!

**Comment by ashtru** [comment]
This warning is given only for anonymous types present in the [AnetAPI schema XSD](https://api.authorize.net/xml/v1/schema/AnetApiSchema.xsd). 

Pyxb library is used to generate classes/elements from the above schema. When nested elements have the possibility of **name clashes** of the same element being used as a child of another object with a different type, Pyxb avoids this by naming these elements with CTD_ANON_## .

If you see the schema above, some of the fields like _profile_ have different types (e.g. _anet:subscriptionCustomerProfileType_, _anet:customerProfilePaymentType_ ) when part of different type of requests. As such, there are multiple resolutions possible and the warning is generated. **It's not an error, and not a source of concern.**

**Comment by sampocs** [comment]
Got it - thank you for the reply!
