### ISSUE TITLE
Check whether ARB Subscription has successfully processed

### ISSUE THREAD

**Issue by lighth7015** [AuthorizeNet/sdk-python#119]
Good afternoon,

I am looking to determine whether the credit or debit card associated with an ARB has been successfully processed or declined. It seems the only way to reliably do this is with API hooks?

Thank you,

**Comment by ashtru** [comment]
You can get the list of transactions ran successfully for an ARB subscription.
In the request, _includeTransactions_ flag has to be set as true ([GetSubscription example](https://github.com/AuthorizeNet/sample-code-php/blob/master/RecurringBilling/get-subscription.php#L25)).
And then you can traverse the array of transactions returned in the response ([GetSubscription example](https://github.com/AuthorizeNet/sample-code-php/blob/master/RecurringBilling/get-subscription.php#L46&L51)).

Also note that the first transaction for a subscription will happen on the _startDate_ for that subscription.

**Comment by lighth7015** [comment]
Thank you!

**Comment by ashtru** [comment]
The above sample codes shared were in PHP.

You can use Python code similar to this PR:
**https://github.com/AuthorizeNet/sample-code-python/pull/43**

In Request code:
`request.includeTransactions = True`
In Response code:
```
if (response.messages.resultCode=="Ok"):
        print ("Subscription Name : %s" % response.subscription.name)
        print ("Subscription Amount: %s" % response.subscription.amount)
        for transaction in response.subscription.arbTransactions.arbTransaction:
            print "Transaction id: %d" % transaction.transId
```
Please try this out, and see if this works for you :)

**Comment by gnongsie** [comment]
Hi all,

Based on the response given by @ashtru , I'm closing this issue.

Kindly reopen this if the issue persists.
