### ISSUE TITLE
Leading 0's In Zip Codes Being Eaten

### ISSUE THREAD

**Issue by paujur** [AuthorizeNet/sdk-python#121]
Hey guys. It looks like you guys convert a zip code `string` that we give you into an `int`. Problem is that zip codes can start with a 0. And because you guys convert the `string` to an `int`, the 0 is getting dropped.

Because of this, some of our users are unable to make payments; their card gets declined for having the wrong address.

**Comment by gnongsie** [comment]
Hi @paujur ,

Thanks for bringing this to our attention.

From our investigation, it seems that a dependency `lxml` automatically considers a number as an integer.

A solution for your problem is to use the `.text` property which will convert this integer into a string so that the zip code can be displayed properly.

Do let us know if you have any further issues with this.

**Comment by paujur** [comment]
Hi @gnongsie,

Are you suggesting we edit our code or edit this library for the time being? I don't think the issue can/should be resolved on our end. It should be your code that needs to use `.text` on that field. So it's either this library or in your backend which submits the (wrong) zipcode when pulling the stored payment profile.

Since our uses a string and the authorize.net dashboard shows the leading zero properly, it seems like it's your backend misinterpreting the string as an integer.

**Comment by gnongsie** [comment]
Hi @paujur ,

Forgive me for not being clear.

What I'm trying to tell you is that we have investigated your problem, providing **"00628"** as the zip code for the transaction. I have checked this in [Charge a Credit Card](https://github.com/gnongsie/sample-code-python/blob/master/PaymentTransactions/charge-credit-card.py) sample code. And I am able to create a transaction without any issues. I can also verify that by using the [Get Transaction Details API](https://developer.authorize.net/api/reference/index.html#transaction-reporting-get-transaction-details).

I may be wrong in understanding which API you are using. But I see no issues with the SDK in this flow. 

Perhaps, if you can provide me more information about the particular flow that you are using, I can troubleshoot this further.

Regards,
Gabriel

**Comment by paujur** [comment]
Hi @gnongsie,

So we're finding the issue when using payment profiles, not when submitting addresses directly when creating the transaction. We're also not seeing the issue when creating payment profiles, so it has to be something internal to your side.

**Comment by chsriniv9** [comment]
Based on @gnongsie instructions above closing this issue. Please feel free to re-open if any further support needed.
