### ISSUE TITLE
WARNING Multiple accepting paths for <class 'authorizenet.apicontractsv1.CTD_ANON_##'>

### ISSUE THREAD

**Issue by vinaychetu** [AuthorizeNet/sdk-python#133]
Hi There,
I'm getting below errors(or some related ones) on my console while charging a credit card(or creating a subscription):

WARNING Multiple accepting paths for <class 'authorizenet.apicontractsv1.CTD_ANON_9'>
WARNING Multiple accepting paths for <class 'authorizenet.apicontractsv1.CTD_ANON_8'>
WARNING Multiple accepting paths for {AnetApi/xml/v1/schema/AnetApiSchema.xsd}transactionResponse

Currently, I'm testing these using Sandbox Credentials for Django(v1.8) using Python-sdk and have not tested on production.
Also, tell me if these are the matter of concern before going live.

**Comment by kikmak42** [comment]
Hi @vinaychetu 

Thank you for raising this issue, we looked into this warning and found these warnings are issued by PyXb.

Whenever there are nested elements and have the possibility of name clashes, PyXb issues these warnings.
Current in our API Schema we have some of the fields like profile, order of different types used in different type of requests, thus we are getting this warning. 

Thus, you need not worry about this and feel free to raise any other concerns.

Happy Coding!
Kaushik
