### ISSUE TITLE
Get Customer Profile Transaction List - 'getTransactionListForCustomerResponse' not defined

### ISSUE THREAD

**Issue by parkermccrady** [AuthorizeNet/sdk-python#141]
As per documentation I was trying to use the Get Customer Profile Transaction List endpoint. After looking over the 'apicontractsv1' file here on github it appears that 'getTransactionListForCustomerResponse' is not defined. I'm unable to use the SDK to access the endpoint. 

`Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Parker\Documents\projects\whatever\what\payment\auth_net.py", line 122, in get_customer_profile_transactions
    controller.execute()
  File "C:\Users\Parker\Documents\projects\whatever\venv\lib\site-packages\authorizenet\apicontrollersbase.py", line 161, in execute
    if type(self.getresponseclass()) != type(self._mainObject):
  File "C:\Users\Parker\Documents\projects\whatever\venv\lib\site-packages\authorizenet\apicontrollers.py", line 709, in getresponseclass
    return apicontractsv1.getTransactionListForCustomerResponse()
AttributeError: module 'authorizenet.apicontractsv1' has no attribute 'getTransactionListForCustomerResponse'
`

**Comment by gnongsie** [comment]
Hi @parkermccrady ,
Thanks for bringing this to our attention. We will be looking into this. Kindly bear with us while we investigate it.

**Comment by loveland24** [comment]
I'm experiencing the same issue, is there any updates on this error?

**Comment by gnongsie** [comment]
Hi,
We have a fix (#142) in place for this issue. It will be released in the next version.

Kindly bear with us in the meantime.

**Comment by parkermccrady** [comment]
I've been bearing with you guys. Any estimate when the next update will be?

**Comment by gnongsie** [comment]
Hi,
This has been released. Please update to the latest version of the SDK (v1.1.3)

**Comment by gnongsie** [comment]
Closing this issue as it was fixed in v1.1.3
