### ISSUE TITLE
Python 3.10 vs pyxb EoL

### ISSUE THREAD

**Issue by rbour** [AuthorizeNet/sdk-python#151]
Python 3.10 has moved abstract base classes from collections to collections.abc available since Python 3.3. This has broken pyxb and, therefore, imports for authorizenet/sdk-python.

There has been [a pyxb pull request](https://github.com/pabigot/pyxb/pull/111) pending for nearly 3 years that would likely fix this specific problem, but the [pyxb author has indicated](https://github.com/pabigot/pyxb/issues/100) that the project is at end-of-life without funding or transfer of ownership.

It seems the path to supporting Python 3.10 would involve either:

1. Replace pyxb in the authorizenet/sdk-python project
2. Work with the pyxb author to get that project up to date

Any chance of supporting Python 3.10 in the near future?

**Comment by rhimmelbauer** [comment]
Or any sort of timeline/road map would be valued.

**Comment by yashsamit** [comment]
Any plans?

**Comment by sunsoftdev** [comment]
any update for the support for Python 3.10. is this library still active?

**Comment by scottie** [comment]
holy shit this has been open since 2022..... whats going on guys ???

**Comment by codeyash** [comment]
At this point using requests lib with direct URL makes more sense!

**Comment by dvlprb2** [comment]
Adding these two lines of code just before importing `authorize.net`  resolves the error without requiring any modifications to the package's source files.
![Screenshot (1)](https://github.com/AuthorizeNet/sdk-python/assets/24942205/857611b9-21d6-4f8b-8c98-c7b1383ed434)


```
import collections
collections.MutableSequence = collections.abc.MutableSequence
```

**Comment by gnongsie** [comment]
The Python SDK has been tested successfully on v3.6 to v3.12.
We have replaced the offending serialization library with a newer one, which will hopefully not cause more issues like this.
Closing this issue based on that.
