### ISSUE TITLE
Can the authorizenet package be made to support Python 3.12?

### ISSUE THREAD

**Issue by nectario** [AuthorizeNet/sdk-python#159]
I need to use Python 3.12 but I cannot use the authorizenet package. It just won't install.
Can you please make it support Python 3.12?
Thank you!
Nektarios

**Comment by faizan-official** [comment]
I'm looking for the same; support for latest python version 3.12. I even tried 3.9.13 version but their sdk didn't work as PyXb library  is outdated. Please upgrade this sdk to use [Pyxb-X](https://github.com/renalreg/PyXB-X) or provide Rest APIs so we can easily use it. Thank you.

**Comment by mike6626** [comment]
Is this repo even active anymore at this point? I feel like with Auth.net being under so many companies now, they have no idea what is what anymore.

**Comment by RemmyLee** [comment]
A little old, but to fix this, you need to edit the following file:

site-packages/pyxb/binding/content.py

On line 799, (import collections), change it to the following:

```
import collections
try:
    from collections import abc
    collections.MutableMapping = abc.MutableMapping
except:
    pass
```
    
    On line 811 (class _PluralBinding (collections.MutableSequence):), change it as follows:
`class _PluralBinding (collections.abc.MutableSequence):`

This will allow the authorizenet module to run again.

**Comment by gnongsie** [comment]
The Python SDK has been tested successfully on v3.6 to v3.12.
Closing this issue based on that.
