### ISSUE TITLE
API always uses sandbox

### ISSUE THREAD

**Issue by fxjeane** [AuthorizeNet/sdk-python#24]
There seems to be a bug on the python SDK. It is hardcoded to always use the sandbox. The issue can bee seen on the APIOperationBase(APIOperationBaseInterface) class on the execute method.

I have fixed the issue on my fork by just changing it to PRODUCTION. The way the code is set right now, there is no way to override this behavior.

Cheers

**Comment by brianmc** [comment]
Hi @fxjeane, we're looking at this right now and should have an update available shortly.

Thanks for reporting this issue.

Brian

**Comment by brianmc** [comment]
Hi @fxjeane we have an updated package available 1.0.6 (pip install --upgrade authorizenet) and also an updated readme to show setting the production environment.

Thanks again for reporting the issue.
