### ISSUE TITLE
Content handling error

### ISSUE THREAD

**Issue by Snipa22** [AuthorizeNet/sdk-python#34]
Hello,

There's a couple of changes that I've noted are needed for Python 3.5 support, specifically in relation to how meta-classes are handled, as well as the various print() requirements.  In addition to this, a couple constants need to be made into binary fields, not huge stuff.

The main issue I'm running into is that the current version here doesn't support the new 'entryMode' field on the transactionResponse.  Having enabled the production XSD and rebuilding it, it appears that pyxb or the class is breaking on an error with accountType.

I also noted that this system swallows exceptions, leading to situations where our systems were finishing a transaction and not aborting, as our try-excepts were not tripping thanks to the logging being sent to logging.debug, rather than sending up an exception.

Any chance these could be looked into?  My branch is fairly hacked up, and likely will break py 2.x support.

Thanks!
Alexander Blair

**Comment by brianmc** [comment]
Hi @Snipa22, latest release 1.0.0 (https://github.com/AuthorizeNet/sdk-python/releases) addresses the entryMode issue. PyPI package for 1.0.9 also released.

We will look into the 3.5 support issues but wanted to update on the blocking issues as soon as we could.

**Comment by Snipa22** [comment]
Thanks!  Looks like the 1.0.9 release worked, I've updated my branch for 3.5 support:
https://github.com/Snipa22/sdk-python/commit/fc3b424a484ffeea7643ab8129cacb0437d072d6

And confirmed this is working on 3.5, as we're not using 2.x, I've yet to test support with that, but these are the changes needed so it'll run properly.

Thank you!
