### ISSUE TITLE
IncompleteElementContentError - Bank Refund

### ISSUE THREAD

**Issue by arckannan** [AuthorizeNet/sdk-python#77]
Greetings!
I get this error when I attempt bank eCheck refund. Same code works for CC refunds. Need help to solve the problem. Code follows. Thanks.

def refundTransaction(refTransId, tag, amount):
                ret = 0
                #first instantiate a CustomerProfile Object using policy id
                print("Refunding Txn id: %s" % refTransId)
                try:
                                obj = ChargeTransaction.objects.get(transaction_id=refTransId)
                except:
                                print ("Failed to get ChargeTransaction for charge id: %s" % refTransId)
                                return ret
 
                merchantAuth = apicontractsv1.merchantAuthenticationType()
                merchantAuth.name = security_tokens['LOGIN_ID']
                merchantAuth.transactionKey = security_tokens["TRANSACTION_KEY"]
 
                payment = apicontractsv1.paymentType()
 
                if obj.payment_method=="CC":
                                creditCard = apicontractsv1.creditCardType()
                                creditCard.cardNumber = obj.last_four
                                creditCard.expirationDate = "XXXX"
                                payment.creditCard = creditCard
                else:
                                bankAc = apicontractsv1.bankAccountType()
                                bankAc.accountNumber = "XXXX" + obj.last_four
                                payment.bankAccount = bankAc
 
                transactionrequest = apicontractsv1.transactionRequestType()
                transactionrequest.transactionType = "refundTransaction"
                transactionrequest.amount = Decimal (amount)
                #set refTransId to transId of a settled transaction
                transactionrequest.refTransId = refTransId
                transactionrequest.payment = payment
 
 
                createtransactionrequest = apicontractsv1.createTransactionRequest()
                createtransactionrequest.merchantAuthentication = merchantAuth
                createtransactionrequest.refId = tag
                createtransactionrequest.transactionRequest = transactionrequest
                createtransactioncontroller = createTransactionController(createtransactionrequest)
                if SANDBOX:
                                createtransactioncontroller.setenvironment(constants.SANDBOX)
                else:
                                createtransactioncontroller.setenvironment(constants.PRODUCTION)
 
                createtransactioncontroller.execute()
 
                response = createtransactioncontroller.getresponse()
 
                if response is not None:
                                if response.messages.resultCode == "Ok":
                                                if hasattr(response.transactionResponse, 'messages') == True:
                                                                print ('Successfully created transaction with Transaction ID: %s' % response.transactionResponse.transId);
                                                                print ('Transaction Response Code: %s' % response.transactionResponse.responseCode);
                                                                print ('Message Code: %s' % response.transactionResponse.messages.message[0].code);
                                                                print ('Description: %s' % response.transactionResponse.messages.message[0].description);
                                                else:
                                                                print ('Failed Transaction.');
                                                                if hasattr(response.transactionResponse, 'errors') == True:
                                                                                print ('Error Code:  %s' % str(response.transactionResponse.errors.error[0].errorCode));
                                                                                print ('Error message: %s' % response.transactionResponse.errors.error[0].errorText);
                                else:
                                                print ('Failed Transaction.');
                                                if hasattr(response, 'transactionResponse') == True and hasattr(response.transactionResponse, 'errors') == True:
                                                                print ('Error Code: %s' % str(response.transactionResponse.errors.error[0].errorCode));
                                                                print ('Error message: %s' % response.transactionResponse.errors.error[0].errorText);
                                                else:
                                                                print ('Error Code: %s' % response.messages.message[0]['code'].text);
                                                                print ('Error message: %s' % response.messages.message[0]['text'].text);
                else:
                                print ('Null Response.');
 
                return response

**Comment by arckannan** [comment]
http://developer.authorize.net/api/reference/index.html#payment-transactions-refund-a-transaction

Posting this API reference link, which seems to imply the only request fields needed for bankaccount is the masked account number.

**Comment by Sapbasu15** [comment]
@arckannan, please find the link [Credit a Bank Account](https://developer.authorize.net/api/reference/index.html#payment-transactions-credit-a-bank-account)  to refund a customer using a bank account credit transaction.
sample code : [https://github.com/AuthorizeNet/sample-code-python/blob/master/PaymentTransactions/credit-bank-account.py](https://github.com/AuthorizeNet/sample-code-python/blob/master/PaymentTransactions/credit-bank-account.py)
Let us know if we can close this issue.

**Comment by muktadiur** [comment]
why this is closed? in sample code you need to provide routingNumber, accountType etc. but the question was when you've only transaction_id and accountNumber last_4 digit then why IncompleteElementContentError?
