### ISSUE TITLE
Python lib creashes with pip 10. AttributeError: module 'pip._vendor.requests' has no attribute 'Session'

### ISSUE THREAD

**Issue by cisarpavel** [AuthorizeNet/sdk-python#97]
Pip version: 10.0.0
Python version: python 3.5.2
Operating system: Linux mint 18.3
Description:
AttributeError: module 'pip._vendor.requests' has no attribute 'Session'

After upgrading to pip I'm seeing this error and project env is now broken.

Python lib obviously import internal module of pip. Correct fix mentioned on https://github.com/pypa/pip/issues/5267.

**Comment by codeyash** [comment]
Problem source. In authorizenet/apicontrollersbase.py, line 11, in <module>
 `from pip._vendor import requests`

We should install requests separately as dependency and shouldn't not rely on pip. 
convert above line  below line. 
`import requests`

[Pip guys suggested this.](https://github.com/pypa/pip/issues/5267)

**Comment by Sapbasu15** [comment]
@cisarpavel we already have issues opened for the same vendored request package dependency. We'll change the request to explicit dependency in the next version.

**Comment by evanstern** [comment]
A speedy resolution on this would certainly be appreciated.

The only way I can fix this right now on a dockerized instance is to downgrade pip to 9.0.3.

**Comment by spartan42895** [comment]
how do you downgrade?

**Comment by tgi01054** [comment]
@spartan42895 
Thanks for comment
Yes. I did downgrade to 9.0.3.

**Comment by evanstern** [comment]
@spartan42895 I did it by adding a line to the requirements.txt file like:

```
pip==9.0.3
```

If you're using Docker to install requirements via requirements.txt then that will do it.

Otherwise just do a `pip install pip==9.0.3`

**Comment by codeyash** [comment]
15 days no solution! 
Need to change one line which I already mentioned.
Dev team is quite busy ;)

**Comment by theonewolf** [comment]
Agreed, the fact that it is named `_vendor` implies that it is private and should not be used outside of `pip`.

Relying on another libraries vendored packages is a very dangerous practice.

**Comment by CRiva** [comment]
is it not possible for the devs to release a hotfix patch release, rather than making us wait and struggle through these errors until the next sdk version comes out?

**Comment by theonewolf** [comment]
We've already migrated to Stripe.

**Comment by sanaani** [comment]
Still waiting...

**Comment by chsriniv9** [comment]
We are in the process of releasing the sdk with the fix

**Comment by fernandezjose** [comment]
#107

**Comment by Sapbasu15** [comment]
we have already merged PR #102 for this and will release official new version next week.

**Comment by chsriniv9** [comment]
Fix is part of new sdk release[1.1.0](https://github.com/AuthorizeNet/sdk-python/releases/tag/1.1.0)

**Comment by codeyash** [comment]
Feeling is..finally :)

**Comment by chzhangdi** [comment]
I meet the same error in kvm, downgrade pip version didn't work otherwise...
The way I fix this, is to remove the recently pip/wheel/setuptools files with type whl. 
Hope this can make some help.
