### ISSUE TITLE
Refactor Implicit Code Depending on `pip` Upstream Vendored Library

### ISSUE THREAD

**Issue by theonewolf** [AuthorizeNet/sdk-python#98]
You should explicitly pin the versions of libraries you use, and not import private, vendored libraries from your dependencies.

This line must be changed to import the normal `requests` library, and also add a version of requests as an explicit dependency: 

https://github.com/AuthorizeNet/sdk-python/blob/e2c7c9ebcd97b8e225245886588b306e17ddcffc/authorizenet/apicontrollersbase.py#L11

This issue is related to #97.

**Comment by pwag42** [comment]
This is the same as issues #95, #96, and #97

**Comment by theonewolf** [comment]
Thanks for point that out.  Maybe we should close this and consolidate into the other issues?

**Comment by pwag42** [comment]
That's a good idea.

**Comment by Sapbasu15** [comment]
We have merged the pull request #102 for the issues and will release new sdk version on PyPi soon.

**Comment by chsriniv9** [comment]
Fix is part of new sdk release[1.1.0](https://github.com/AuthorizeNet/sdk-python/releases/tag/1.1.0)

**Comment by theonewolf** [comment]
Thanks @chsriniv9!
